version: "3.9"
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: go.postgres
    ports:
      - 5432:5432
    networks:
      - mi-red
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

networks:
  mi-red:
    driver: bridge